apiVersion: v1
kind: Service
metadata:
  name: object-detection-service
spec:
  type: NodePort
  selector:
    app: object-detection
  ports:
    - protocol: TCP
      port: 1070
      targetPort: 1070
      nodePort: 30023