apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-detection-deployment
spec:
  selector:
    matchLabels:
      app: object-detection
  replicas: 1
  template:
    metadata:
      labels:
        app: object-detection
    spec:
      containers:
      - name: object-detection
        image: flask-app:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1070
        resources:  
          requests:
            cpu: "500m"  
            memory: "512Mi" 
          limits:
            cpu: "500m" 
            memory: "512Mi" 